#!/bin/bash

case $1 in
(cyg|cygwin|cygwin-debug)
perl -I cons ./cons/cons.pl -- --toolset=gcc,cygwin,boost,clo --boost-root-dir=/d/boost-1.31.0 -v3 ;;
(cygwin-release)
perl -I cons ./cons/cons.pl -- --toolset=gcc,cygwin,boost,clo --build=Release -v3 ;;
(win-release)
/d/perl/bin/perl -I cons ./cons/cons.pl -- --toolset=msvc70,cygwin,boost,clo  --build=Release -v3 ;;
(doc)
/d/perl/bin/perl -I cons ./cons/cons.pl doc -- --toolset=doxygen -v3 && cd doc/docsys && ./docsys dgd && ./docsys doxy ;;
(clean)
/d/perl/bin/perl -I cons ./cons/cons.pl -- clean ;;
(win|win-debug|*)
/d/perl/bin/perl -I cons ./cons/cons.pl -- --toolset=msvc70,cygwin,boost,clo --boost-root-dir=d:/boost -v3 ;;
esac

# 
# Local Variables:
# compile-command: "bash -c \"./bldme win\""
# End:
#
