#!/bin/sh

unset QTDIR

autoconf

case "$1" in
*cyg* | *CYG*) 
./configure --enable-debug --without-stlport --with-cvs="cvs.exe" PERL="/d/perl/bin/perl.exe" WEBMAKE="d:/perl/bin/webmake" DOXYGEN="/d/Progra~1/doxygen/bin/doxygen.exe" ;;
*unix* | *UNIX* | *linux* | *LINUX*)
./configure --enable-debug --without-stlport --with-cvs="cvs" ;;
*)
./configure --with-msvc --without-pch --enable-debug --with-cvs="cvs.exe" PERL="/d/perl/bin/perl.exe" WEBMAKE="d:/perl/bin/webmake" DOXYGEN="/d/Progra~1/doxygen/bin/doxygen.exe" ;;
esac

