/* dgDebugOpt.h */

/* File autogenerated by gengetopt version 2.4  */

#ifndef _dgDebugOpt_h
#define _dgDebugOpt_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Don't define PACKAGE and VERSION if we use automake.  */
#ifndef PACKAGE
/* ******* WRITE THE NAME OF YOUR PROGRAM HERE ******* */
#define PACKAGE ""
#endif
#ifndef VERSION
/* ******* WRITE THE VERSION OF YOUR PROGRAM HERE ******* */
#define VERSION ""
#endif

struct dgd_gengetopt_args_info {
  char * debug_file_arg;	/* Debug output file.  */
  int debug_min_width_arg;	/* Default minimum output width.  */
  int debug_max_width_arg;	/* Default maximum output width.  */
  int debug_indent_step_arg;	/* Default indent step.  */
  int debug_allow_wrap_flag;	/* Allow character wrap by default (default=on).  */
  int debug_allow_word_wrap_flag;	/* Allow word wrap by default (default=on).  */
  char * debug_space_characters_arg;	/* Characters separating words.  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int debug_file_given ;	/* Whether debug-file was given.  */
  int debug_min_width_given ;	/* Whether debug-min-width was given.  */
  int debug_max_width_given ;	/* Whether debug-max-width was given.  */
  int debug_indent_step_given ;	/* Whether debug-indent-step was given.  */
  int debug_allow_wrap_given ;	/* Whether debug-allow-wrap was given.  */
  int debug_allow_word_wrap_given ;	/* Whether debug-allow-word-wrap was given.  */
  int debug_space_characters_given ;	/* Whether debug-space-characters was given.  */
} ;

int dgd_cmdline_parser (int argc, char * const *argv, struct dgd_gengetopt_args_info *args_info);

void dgd_cmdline_parser_print_help(void);
void dgd_cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _dgDebugOpt_h */
