/*
  File autogenerated by gengetopt version 2.4  
  generated with the following command:
  gengetopt --no-handle-help --no-handle-version --no-handle-error --file-name=dgDebugOpt --func-name=dgd_cmdline_parser 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
/* Check for configure's getopt check result.  */
#ifndef HAVE_GETOPT_LONG
#include "getopt.h"
#else
#include <getopt.h>
#endif

#include "dgDebugOpt.h"


void
dgd_cmdline_parser_print_version (void)
{
  printf ("%s %s\n", PACKAGE, VERSION);
}

void
dgd_cmdline_parser_print_help (void)
{
  dgd_cmdline_parser_print_version ();
  printf("\n"
"Usage: %s [OPTIONS]...\n\
   -h         --help                           Print help and exit\n\
   -V         --version                        Print version and exit\n\
   -dSTRING   --debug-file=STRING              Debug output file\n\
   -mINT      --debug-min-width=INT            Default minimum output width\n\
   -MINT      --debug-max-width=INT            Default maximum output width\n\
   -sINT      --debug-indent-step=INT          Default indent step\n\
   -w         --debug-allow-wrap               Allow character wrap by default (default=on)\n\
   -W         --debug-allow-word-wrap          Allow word wrap by default (default=on)\n\
              --debug-space-characters=STRING  Characters separating words\n\
", PACKAGE);
}


static char *
gengetopt_strdup (char * s)
{
  char * n, * pn, * ps = s;
  while (*ps) ps++;
  n = (char *) malloc (1 + ps - s);
  if (n != NULL)
    {
      for (ps=s,pn=n; *ps; ps++,pn++)
        *pn = *ps;
      *pn = 0;
    }
  return n;
}


int
dgd_cmdline_parser (int argc, char * const *argv, struct dgd_gengetopt_args_info *args_info)
{
  int c;	/* Character of the parsed option.  */
  int missing_required_options = 0;	

  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->debug_file_given = 0 ;
  args_info->debug_min_width_given = 0 ;
  args_info->debug_max_width_given = 0 ;
  args_info->debug_indent_step_given = 0 ;
  args_info->debug_allow_wrap_given = 0 ;
  args_info->debug_allow_word_wrap_given = 0 ;
  args_info->debug_space_characters_given = 0 ;
#define clear_args() { \
  args_info->debug_file_arg = NULL; \
  args_info->debug_allow_wrap_flag = 1;\
  args_info->debug_allow_word_wrap_flag = 1;\
  args_info->debug_space_characters_arg = NULL; \
}

  clear_args();

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "debug-file",	1, NULL, 'd' },
        { "debug-min-width",	1, NULL, 'm' },
        { "debug-max-width",	1, NULL, 'M' },
        { "debug-indent-step",	1, NULL, 's' },
        { "debug-allow-wrap",	0, NULL, 'w' },
        { "debug-allow-word-wrap",	0, NULL, 'W' },
        { "debug-space-characters",	1, NULL, 0 },
        { NULL,	0, NULL, 0 }
      };

      c = getopt_long (argc, argv, "hVd:m:M:s:wW", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          if (args_info->help_given)
            {
              fprintf (stderr, "%s: `--help' (`-h') option given more than once\n", PACKAGE);
              clear_args ();
              return (1);
            }
          args_info->help_given = 1;
          return 0;

        case 'V':	/* Print version and exit.  */
          if (args_info->version_given)
            {
              fprintf (stderr, "%s: `--version' (`-V') option given more than once\n", PACKAGE);
              clear_args ();
              return (1);
            }
          args_info->version_given = 1;
          return 0;

        case 'd':	/* Debug output file.  */
          if (args_info->debug_file_given)
            {
              fprintf (stderr, "%s: `--debug-file' (`-d') option given more than once\n", PACKAGE);
              clear_args ();
              return (1);
            }
          args_info->debug_file_given = 1;
          args_info->debug_file_arg = gengetopt_strdup (optarg);
          break;

        case 'm':	/* Default minimum output width.  */
          if (args_info->debug_min_width_given)
            {
              fprintf (stderr, "%s: `--debug-min-width' (`-m') option given more than once\n", PACKAGE);
              clear_args ();
              return (1);
            }
          args_info->debug_min_width_given = 1;
          args_info->debug_min_width_arg = atoi (optarg);
          break;

        case 'M':	/* Default maximum output width.  */
          if (args_info->debug_max_width_given)
            {
              fprintf (stderr, "%s: `--debug-max-width' (`-M') option given more than once\n", PACKAGE);
              clear_args ();
              return (1);
            }
          args_info->debug_max_width_given = 1;
          args_info->debug_max_width_arg = atoi (optarg);
          break;

        case 's':	/* Default indent step.  */
          if (args_info->debug_indent_step_given)
            {
              fprintf (stderr, "%s: `--debug-indent-step' (`-s') option given more than once\n", PACKAGE);
              clear_args ();
              return (1);
            }
          args_info->debug_indent_step_given = 1;
          args_info->debug_indent_step_arg = atoi (optarg);
          break;

        case 'w':	/* Allow character wrap by default.  */
          args_info->debug_allow_wrap_flag = !(args_info->debug_allow_wrap_flag);
          break;

        case 'W':	/* Allow word wrap by default.  */
          args_info->debug_allow_word_wrap_flag = !(args_info->debug_allow_word_wrap_flag);
          break;

        
        case 0:	/* Long option with no short option */
          /* Characters separating words.  */
          if (strcmp (long_options[option_index].name, "debug-space-characters") == 0)
          {
            if (args_info->debug_space_characters_given)
              {
                fprintf (stderr, "%s: `--debug-space-characters' option given more than once\n", PACKAGE);
                clear_args ();
                return (1);
              }
            args_info->debug_space_characters_given = 1;
            args_info->debug_space_characters_arg = gengetopt_strdup (optarg);
            break;
          }

        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          return (1);

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c\n", PACKAGE, c);
          abort ();
        } /* switch */
    } /* while */

  if ( missing_required_options )
    return (1);


  return 0;
}
