/* dgDebugOpt.h */

/* File autogenerated by gengetopt version 2.4  */

#ifndef _dgDebugOpt_h
#define _dgDebugOpt_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Don't define PACKAGE and VERSION if we use automake.  */
#if defined PACKAGE
#  undef PACKAGE
#endif
#define PACKAGE "dgd"
#if defined VERSION
#  undef VERSION
#endif
#define VERSION "Unknown"

struct dgd_gengetopt_args_info {
  int trace_version_flag;	/* Print dgd version and exit (default=off).  */
  int trace_help_flag;	/* Print debug help and exit (default=off).  */
  int trace_enable_flag;	/* Enable debug (default=off).  */
  char * trace_main_file_arg;	/* Primary debug output file.  */
  int trace_min_width_arg;	/* Default minimum output width.  */
  int trace_max_width_arg;	/* Default maximum output width.  */
  int trace_indent_step_arg;	/* Default indent step.  */
  int trace_allow_wrap_flag;	/* Allow character wrap by default (default=on).  */
  int trace_allow_word_wrap_flag;	/* Allow word wrap by default (default=on).  */
  char * trace_space_characters_arg;	/* Characters separating words.  */
  char * trace_turn_on_arg;	/* Regexp on channels to turn on.  */
  char * trace_turn_off_arg;	/* Regexp on channels to turn off.  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int trace_version_given ;	/* Whether trace-version was given.  */
  int trace_help_given ;	/* Whether trace-help was given.  */
  int trace_enable_given ;	/* Whether trace-enable was given.  */
  int trace_main_file_given ;	/* Whether trace-main-file was given.  */
  int trace_min_width_given ;	/* Whether trace-min-width was given.  */
  int trace_max_width_given ;	/* Whether trace-max-width was given.  */
  int trace_indent_step_given ;	/* Whether trace-indent-step was given.  */
  int trace_allow_wrap_given ;	/* Whether trace-allow-wrap was given.  */
  int trace_allow_word_wrap_given ;	/* Whether trace-allow-word-wrap was given.  */
  int trace_space_characters_given ;	/* Whether trace-space-characters was given.  */
  int trace_turn_on_given ;	/* Whether trace-turn-on was given.  */
  int trace_turn_off_given ;	/* Whether trace-turn-off was given.  */
} ;

int dgd_cmdline_parser (int argc, char * const *argv, struct dgd_gengetopt_args_info *args_info);

void dgd_cmdline_parser_print_help(void);
void dgd_cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _dgDebugOpt_h */
